"""Database creation

Revision ID: afbf3f10d134
Revises: a0f5d1256c86
Create Date: 2024-07-09 23:11:24.125942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbf3f10d134'
down_revision: Union[str, None] = 'a0f5d1256c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessory', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('smartphone', sa.Column('description', sa.String(), nullable=False))
    op.add_column('smartphone', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smartphone', 'is_verified')
    op.drop_column('smartphone', 'description')
    op.drop_column('accessory', 'is_verified')
    # ### end Alembic commands ###
